// Curated "featured" companies for the Earnings Hub: clean display names + a logo
// domain (favicon fallback). These always appear in the "Top companies" view; the
// view also auto-includes any company with a market cap >= $10B, so big hitters are
// covered even if they're not listed here. `logo` optionally overrides with a
// checked-in asset path (e.g. 'logos/AAPL.svg').
export const WATCHLIST = [
  // Mega-cap tech
  { symbol: 'AAPL', name: 'Apple', domain: 'apple.com' },
  { symbol: 'MSFT', name: 'Microsoft', domain: 'microsoft.com' },
  { symbol: 'NVDA', name: 'NVIDIA', domain: 'nvidia.com' },
  { symbol: 'GOOGL', name: 'Alphabet (Google)', domain: 'google.com' },
  { symbol: 'AMZN', name: 'Amazon', domain: 'amazon.com' },
  { symbol: 'META', name: 'Meta Platforms', domain: 'meta.com' },
  { symbol: 'AVGO', name: 'Broadcom', domain: 'broadcom.com' },
  { symbol: 'TSLA', name: 'Tesla', domain: 'tesla.com' },
  { symbol: 'ORCL', name: 'Oracle', domain: 'oracle.com' },
  { symbol: 'CRM', name: 'Salesforce', domain: 'salesforce.com' },
  { symbol: 'ADBE', name: 'Adobe', domain: 'adobe.com' },
  { symbol: 'AMD', name: 'AMD', domain: 'amd.com' },
  { symbol: 'INTC', name: 'Intel', domain: 'intel.com' },
  { symbol: 'QCOM', name: 'Qualcomm', domain: 'qualcomm.com' },
  { symbol: 'TXN', name: 'Texas Instruments', domain: 'ti.com' },
  { symbol: 'CSCO', name: 'Cisco', domain: 'cisco.com' },
  { symbol: 'IBM', name: 'IBM', domain: 'ibm.com' },
  { symbol: 'NOW', name: 'ServiceNow', domain: 'servicenow.com' },
  { symbol: 'INTU', name: 'Intuit', domain: 'intuit.com' },
  { symbol: 'NFLX', name: 'Netflix', domain: 'netflix.com' },
  // Financials
  { symbol: 'BRK-B', name: 'Berkshire Hathaway', domain: 'berkshirehathaway.com' },
  { symbol: 'JPM', name: 'JPMorgan Chase', domain: 'jpmorganchase.com' },
  { symbol: 'V', name: 'Visa', domain: 'visa.com' },
  { symbol: 'MA', name: 'Mastercard', domain: 'mastercard.com' },
  { symbol: 'BAC', name: 'Bank of America', domain: 'bankofamerica.com' },
  { symbol: 'WFC', name: 'Wells Fargo', domain: 'wellsfargo.com' },
  { symbol: 'GS', name: 'Goldman Sachs', domain: 'goldmansachs.com' },
  { symbol: 'MS', name: 'Morgan Stanley', domain: 'morganstanley.com' },
  { symbol: 'AXP', name: 'American Express', domain: 'americanexpress.com' },
  { symbol: 'BLK', name: 'BlackRock', domain: 'blackrock.com' },
  { symbol: 'C', name: 'Citigroup', domain: 'citigroup.com' },
  { symbol: 'SPGI', name: 'S&P Global', domain: 'spglobal.com' },
  // Healthcare
  { symbol: 'LLY', name: 'Eli Lilly', domain: 'lilly.com' },
  { symbol: 'UNH', name: 'UnitedHealth', domain: 'unitedhealthgroup.com' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', domain: 'jnj.com' },
  { symbol: 'ABBV', name: 'AbbVie', domain: 'abbvie.com' },
  { symbol: 'MRK', name: 'Merck', domain: 'merck.com' },
  { symbol: 'ABT', name: 'Abbott', domain: 'abbott.com' },
  { symbol: 'PFE', name: 'Pfizer', domain: 'pfizer.com' },
  { symbol: 'TMO', name: 'Thermo Fisher', domain: 'thermofisher.com' },
  { symbol: 'AMGN', name: 'Amgen', domain: 'amgen.com' },
  { symbol: 'DHR', name: 'Danaher', domain: 'danaher.com' },
  // Consumer
  { symbol: 'WMT', name: 'Walmart', domain: 'walmart.com' },
  { symbol: 'PG', name: 'Procter & Gamble', domain: 'pg.com' },
  { symbol: 'KO', name: 'Coca-Cola', domain: 'coca-colacompany.com' },
  { symbol: 'PEP', name: 'PepsiCo', domain: 'pepsico.com' },
  { symbol: 'COST', name: 'Costco', domain: 'costco.com' },
  { symbol: 'MCD', name: "McDonald's", domain: 'mcdonalds.com' },
  { symbol: 'HD', name: 'Home Depot', domain: 'homedepot.com' },
  { symbol: 'NKE', name: 'Nike', domain: 'nike.com' },
  { symbol: 'SBUX', name: 'Starbucks', domain: 'starbucks.com' },
  { symbol: 'PM', name: 'Philip Morris', domain: 'pmi.com' },
  { symbol: 'DIS', name: 'Disney', domain: 'disney.com' },
  // Energy & industrials
  { symbol: 'XOM', name: 'Exxon Mobil', domain: 'exxonmobil.com' },
  { symbol: 'CVX', name: 'Chevron', domain: 'chevron.com' },
  { symbol: 'CAT', name: 'Caterpillar', domain: 'caterpillar.com' },
  { symbol: 'LMT', name: 'Lockheed Martin', domain: 'lockheedmartin.com' },
  { symbol: 'BA', name: 'Boeing', domain: 'boeing.com' },
  { symbol: 'HON', name: 'Honeywell', domain: 'honeywell.com' },
  { symbol: 'GE', name: 'GE Aerospace', domain: 'ge.com' },
  { symbol: 'RTX', name: 'RTX', domain: 'rtx.com' },
  { symbol: 'DE', name: 'Deere', domain: 'deere.com' },
  { symbol: 'UNP', name: 'Union Pacific', domain: 'unionpacific.com' },
  { symbol: 'UPS', name: 'UPS', domain: 'ups.com' },
  // Communications, utilities, REIT
  { symbol: 'T', name: 'AT&T', domain: 'att.com' },
  { symbol: 'VZ', name: 'Verizon', domain: 'verizon.com' },
  { symbol: 'CMCSA', name: 'Comcast', domain: 'comcast.com' },
  { symbol: 'NEE', name: 'NextEra Energy', domain: 'nexteraenergy.com' },
  { symbol: 'LIN', name: 'Linde', domain: 'linde.com' },
  { symbol: 'O', name: 'Realty Income', domain: 'realtyincome.com' },
];
